apiVersion: apps/v1
kind: Deployment
metadata:
  name: maken-index-api
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: maken-index-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: maken-index-api
    spec:
      containers:
      - env:
        - name: ES_HOST
          valueFrom:
            configMapKeyRef:
              key: ES_HOST
              name: maken-index-api-config
        - name: ES_SCHEME
          valueFrom:
            configMapKeyRef:
              key: ES_SCHEME
              name: maken-index-api-config
        image: gcr.io/nancy-194708/maken-es-api@sha256:d46963821fc8d8fbcf099eea5a59938c6b0bae78a869236e1957ccf97c264a0d
        imagePullPolicy: IfNotPresent
        name: maken-es-api-sha256-1
        resources:
          # Requests for CPU and memory to be able to autoscale
          requests:
            memory: "512Mi"
            cpu: "250m"
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: maken-api-service
spec:
  type: LoadBalancer
  selector:
    app: maken-index-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
