apiVersion: v1
kind: Service
metadata:
  name: maken-index-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: maken-index
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/component: opensearch-cluster-master
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
