apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: maken-index-ds
  name: maken-index-ds
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: maken-index
      app.kubernetes.io/name: opensearch
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: maken-index
        app.kubernetes.io/name: opensearch
    spec:
      hostPID: true
      containers:
      - name: maken-index
        image: gcr.io/google-containers/startup-script:v1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 0
        env:
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/bash
            sysctl -w vm.max_map_count=262144
            echo "done"

